### ISSUE TITLE
i catch a exception

### ISSUE THREAD

**Issue by FZLCCM** [RainJayTsai/FaceUnclok#1]
12-29 16:15:33.654 7421-7421/org.rainjay.newfaceunlock E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: org.rainjay.newfaceunlock, PID: 7421
                                                                         java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTIN2cv16MinProblemSolver8FunctionE" referenced by "/data/app/org.rainjay.newfaceunlock-1/lib/arm/libjniopencv_core.so"...
                                                                             at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                             at java.lang.System.loadLibrary(System.java:1076)
                                                                             at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726)
                                                                             at org.bytedeco.javacpp.Loader.load(Loader.java:501)
                                                                             at org.bytedeco.javacpp.Loader.load(Loader.java:418)
                                                                             at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
                                                                             at java.lang.Class.classForName(Native Method)
                                                                             at java.lang.Class.forName(Class.java:324)
                                                                             at org.bytedeco.javacpp.Loader.load(Loader.java:473)
                                                                             at org.bytedeco.javacpp.Loader.load(Loader.java:418)
                                                                             at org.bytedeco.javacpp.opencv_face.<clinit>(opencv_face.java:13)
                                                                             at org.bytedeco.javacpp.opencv_face.createLBPHFaceRecognizer(Native Method)
                                                                             at org.rainjay.newfaceunlock.imageutil.FaceRecognizerSingleton.getInstance(FaceRecognizerSingleton.java:28)
                                                                             at org.rainjay.newfaceunlock.RegisterActivity.onCreate(RegisterActivity.java:54)
                                                                             at android.app.Activity.performCreate(Activity.java:6248)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:150)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:168)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                                          Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.rainjay.newfaceunlock-1/base.apk"],nativeLibraryDirectories=[/data/app/org.rainjay.newfaceunlock-1/lib/arm, /data/app/org.rainjay.newfaceunlock-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib, system/vendor/lib, system/vendor/lib/egl, system/lib/hw]]] couldn't find "libgnustl_static.so"
                                                                             at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                             at java.lang.System.loadLibrary(System.java:1076)
                                                                             at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726)
                                                                             at org.bytedeco.javacpp.Loader.load(Loader.java:492)
                                                                             at org.bytedeco.javacpp.Loader.load(Loader.java:418) 
                                                                             at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10) 
                                                                             at java.lang.Class.classForName(Native Method) 
                                                                             at java.lang.Class.forName(Class.java:324) 
                                                                             at org.bytedeco.javacpp.Loader.load(Loader.java:473) 
                                                                             at org.bytedeco.javacpp.Loader.load(Loader.java:418) 
                                                                             at org.bytedeco.javacpp.opencv_face.<clinit>(opencv_face.java:13) 
                                                                             at org.bytedeco.javacpp.opencv_face.createLBPHFaceRecognizer(Native Method) 
                                                                             at org.rainjay.newfaceunlock.imageutil.FaceRecognizerSingleton.getInstance(FaceRecognizerSingleton.java:28) 
                                                                             at org.rainjay.newfaceunlock.RegisterActivity.onCreate(RegisterActivity.java:54) 
                                                                             at android.app.Activity.performCreate(Activity.java:6248) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:168) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5845) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by RainJayTsai** [comment]
Did you run your Gradle  correct ?
